<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_product_type_group".
 *
 * @property integer $id
 * @property integer $product_type_id
 * @property integer $group_id
 *
 * @property \d3yii2\d3product\models\D3productGroup $group
 * @property \d3yii2\d3product\models\D3productProductType $productType
 * @property string $aliasModel
 */
abstract class D3productProductTypeGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_product_type_group';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['product_type_id', 'group_id'], 'required'],
            'smallint Unsigned' => [['id','product_type_id','group_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['group_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productGroup::className(), 'targetAttribute' => ['group_id' => 'id']],
            [['product_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productProductType::className(), 'targetAttribute' => ['product_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'product_type_id' => Yii::t('d3labels', 'Product Type'),
            'group_id' => Yii::t('d3labels', 'Group'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'product_type_id' => Yii::t('d3labels', 'Product Type'),
            'group_id' => Yii::t('d3labels', 'Group'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productGroup::className(), ['id' => 'group_id'])->inverseOf('d3productProductTypeGroups');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductType()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productProductType::className(), ['id' => 'product_type_id'])->inverseOf('d3productProductTypeGroups');
    }




}
