<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_code_type".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $name
 *
 * @property \d3yii2\d3product\models\D3productCodes[] $d3productCodes
 * @property string $aliasModel
 */
abstract class D3productCodeType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_code_type';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['sys_company_id', 'name'], 'required'],
            'tinyint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['name'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'sys_company_id' => Yii::t('d3labels', 'Sys Company ID'),
            'name' => Yii::t('d3labels', 'Name'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'name' => Yii::t('d3labels', 'Name'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3productCodes()
    {
        return $this->hasMany(\d3yii2\d3product\models\D3productCodes::className(), ['type_id' => 'id'])->inverseOf('type');
    }




}
