<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_attributes".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $type_attribute_id
 * @property string $value
 *
 * @property \d3yii2\d3product\models\D3productProduct $product
 * @property \d3yii2\d3product\models\D3productTypeAttributes $typeAttribute
 * @property string $aliasModel
 */
abstract class D3productAttributes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_attributes';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['product_id', 'type_attribute_id'], 'required'],
            'smallint Unsigned' => [['product_id','type_attribute_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['value'], 'string', 'max' => 50],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productProduct::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['type_attribute_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productTypeAttributes::className(), 'targetAttribute' => ['type_attribute_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'product_id' => Yii::t('d3labels', 'Product'),
            'type_attribute_id' => Yii::t('d3labels', 'Product Type'),
            'value' => Yii::t('d3labels', 'Value'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'product_id' => Yii::t('d3labels', 'Product'),
            'type_attribute_id' => Yii::t('d3labels', 'Product Type'),
            'value' => Yii::t('d3labels', 'Value'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productProduct::className(), ['id' => 'product_id'])->inverseOf('d3productAttributes');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeAttribute()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productTypeAttributes::className(), ['id' => 'type_attribute_id'])->inverseOf('d3productAttributes');
    }




}
