<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_product_price".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $price_type_id
 * @property string $price
 *
 * @property \d3yii2\d3product\models\D3productPriceType $priceType
 * @property \d3yii2\d3product\models\D3productProduct $product
 * @property string $aliasModel
 */
abstract class D3productProductPrice extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_product_price';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['product_id', 'price_type_id'], 'required'],
            'tinyint Unsigned' => [['price_type_id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['product_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['price'], 'number'],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productProduct::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['price_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productPriceType::className(), 'targetAttribute' => ['price_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'product_id' => Yii::t('d3labels', 'Product'),
            'price_type_id' => Yii::t('d3labels', 'Price Type'),
            'price' => Yii::t('d3labels', 'Price'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'product_id' => Yii::t('d3labels', 'Product'),
            'price_type_id' => Yii::t('d3labels', 'Price Type'),
            'price' => Yii::t('d3labels', 'Price'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPriceType()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productPriceType::className(), ['id' => 'price_type_id'])->inverseOf('d3productProductPrices');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productProduct::className(), ['id' => 'product_id'])->inverseOf('d3productProductPrices');
    }




}
