<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_codes".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $type_id
 * @property string $code
 *
 * @property \d3yii2\d3product\models\D3productProduct $product
 * @property \d3yii2\d3product\models\D3productCodeType $type
 * @property string $aliasModel
 */
abstract class D3productCodes extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_codes';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['product_id', 'type_id', 'code'], 'required'],
            'tinyint Unsigned' => [['type_id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['product_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['code'], 'string', 'max' => 50],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productProduct::className(), 'targetAttribute' => ['product_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3product\models\D3productCodeType::className(), 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'product_id' => Yii::t('d3labels', 'Product'),
            'type_id' => Yii::t('d3labels', 'Code Type'),
            'code' => Yii::t('d3labels', 'Code'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints(): array
    {
        return array_merge(parent::attributeHints(), [
            'product_id' => Yii::t('d3labels', 'Product'),
            'type_id' => Yii::t('d3labels', 'Code Type'),
            'code' => Yii::t('d3labels', 'Code'),
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productProduct::className(), ['id' => 'product_id'])->inverseOf('d3productCodes');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\d3yii2\d3product\models\D3productCodeType::className(), ['id' => 'type_id'])->inverseOf('d3productCodes');
    }




}
