<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_input_type".
 *
 * @property integer $id
 * @property string $name
 * @property string $dictioanry_class
 * @property string $validate_rule
 *
 * @property \d3yii2\d3product\models\D3productTypeAttributes[] $d3productTypeAttributes
 * @property string $aliasModel
 */
abstract class D3productInputType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_input_type';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'tinyint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 255],
            [['validate_rule'], 'string'],
            [['name'], 'string', 'max' => 30],
            [['dictioanry_class'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'name' => Yii::t('d3labels', 'Name'),
            'dictioanry_class' => Yii::t('d3labels', 'Dictioanry Class'),
            'validate_rule' => Yii::t('d3labels', 'Validate Rule'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3productTypeAttributes()
    {
        return $this->hasMany(\d3yii2\d3product\models\D3productTypeAttributes::className(), ['input_type_id' => 'id'])->inverseOf('inputType');
    }




}
