<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3product\models\base;

use Yii;


/**
 * This is the base-model class for table "d3product_group".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $name
 *
 * @property \d3yii2\d3product\models\D3productProductGroup[] $d3productProductGroups
 * @property \d3yii2\d3product\models\D3productProductTypeGroup[] $d3productProductTypeGroups
 * @property string $aliasModel
 */
abstract class D3productGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3product_group';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['sys_company_id'], 'required'],
            'smallint Unsigned' => [['id','sys_company_id'],'integer' ,'min' => 0 ,'max' => 65535],
            [['name'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3labels', 'ID'),
            'sys_company_id' => Yii::t('d3labels', 'Sys Company ID'),
            'name' => Yii::t('d3labels', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3productProductGroups()
    {
        return $this->hasMany(\d3yii2\d3product\models\D3productProductGroup::className(), ['group_id' => 'id'])->inverseOf('group');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3productProductTypeGroups()
    {
        return $this->hasMany(\d3yii2\d3product\models\D3productProductTypeGroup::className(), ['group_id' => 'id'])->inverseOf('group');
    }




}
